sudo: required
dist: trusty
language: node_js

install:
  - npm install -g gulp
  - npm install
  - pushd qmlify
  - npm install
  - popd
  - pushd quickly
  - npm install
  - popd
  - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
  - sudo apt-get update
  - sudo apt-get -y install qt55declarative
  - sudo apt-get -y install qt55tools
  - sudo apt-get -y install xvfb
  
script:
  - source /opt/qt55/bin/qt55-env.sh
  - xvfb-run -a -s "-screen 0 800x600x24" ctest -V
  - pushd qmlify
  - gulp
  - npm test
  - npm link
  - popd
  - pushd quickly
  - npm build; npm run install-qml; npm test
