language: node_js
install:
  - npm install
  - pushd qmlify
  - npm install
  - popd
  - pushd quickly
  - npm install
  - popd
script:
  - pushd qmlify
  - gulp
  - npm test
  - npm link
  - popd
  - pushd quickly
  - npm build
  - npm run install-qml
  - npm test
